name: Deploy ARM Template

on:
  push:
    branches:
      - main
jobs:
  deploy-virtual-network-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get KV secret
        uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: "WiredCanuck-KeyVault"
          secrets: 'mySecret'  # comma separated list of secret keys that need to be fetched from the Key Vault 
          id: myGetSecretAction
